config/routes.rb
Rails.application.routes.draw do
  root 'static#landing_page'
  resources :reviews
  resources :products
  get '/shoes', to: 'products#shoe_sort'
  get '/apparel', to: 'products#apparel_sort'
  get '/skate', to: 'products#skate_sort'
  get '/videos', to: 'videos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, :url, presence: true

  has_many :reviews, dependent: :destroy

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end
  def shoe_sort
    @shoes = Product.where(category: "shoes")
  end

  def apparel_sort
    @apparel = Product.where(category: "apparel")
  end

  def skate_sort
    @skate = Product.where(category: "skate")
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :url, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price_in_cents %>
    <%= f.number_field :price_in_cents %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_area :url %>
  </div>

  <div class="field">
    <%= f.select(:category, options_for_select( ['skate', 'shoes', 'apparel'])) %>
  </div>

  <!-- <div class="field">
    <%#= f.label :comment %><br>
    <%#= f.text_area :comment %>
  </div> -->

  <% if @product.nil? %>
    <div class="field">
      <%= f.label :product_id %><br>
      <%= f.text_field :product_id %>
    </div>

  <% else %>
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id, disabled: true, value: @product.id %>

  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/apparel_sort.html.erb
<div id="outer" class="flex_column">
  <a href="/" class="home-link"><header id="one">WynSkate</header></a>
  <nav id="two" class="nav-link">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/skate">Skate</a></li>
      <li><a href="/shoes">Shoes</a></li>
      <li><a href="/apparel">Apparel</a></li>
      <li><a href="/videos">Videos</a></li>
    </ul>
  </nav>
  <div id="center">
    <div id="apparel-sort" class="flex_column product-container">
      <% @apparel.each do |item|%>
      <img src="<%= item.url%>" class="shoe-image"/>
      <a href="/products/<%= item.id %>"  class="text-center"><%= item.name %> </a>
      <span class="shoe-desc text-center"><%= item.description %></span>
      <%= item.price_in_cents %>
       <% end %>
    </div>
    <div class="flex_column">
      <aside>
        <h3>Great deals on <br>new products!</h3>
        <img src="<%=Product.all.sample.url%>" />
      </aside>
      <aside>
        <img src="<%=Product.all.sample.url%>" />
        <p>40% off all new products!</p>
      </aside>
    </div>
  </div>
  <footer class="footer-pad">Contact Info <br> Adam Hill Email - ahil0017@gmail.com <br> Jake Sena Email - jakesena1994@gmail.com</footer>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

<h1>Editing review</h1>
<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price in cents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price_in_cents %></td>
        <td><%= product.formatted_price %></td>
        <td><%= product.category %></td>
        <td><img src="<%= product.url %>"/> </td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div id="its-soo-late">
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', root_path %>

</div>

app/views/products/shoe_sort.html.erb
<div id="outer" class="flex_column">
  <a href="/" class="home-link"><header id="one">WynSkate</header></a>
  <nav id="two" class="nav-link">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/skate">Skate</a></li>
      <li><a href="/shoes">Shoes</a></li>
      <li><a href="/apparel">Apparel</a></li>
      <li><a href="/videos">Videos</a></li>
    </ul>
  </nav>
  <div id="center">
    <div id="shoe-sort" class="flex_column product-container">
      <% @shoes.each do |shoe|%>
      <img src="<%= shoe.url%>" class="shoe-image" />
      <a href="/products/<%= shoe.id %>" class="text-center">  <%= shoe.name %> </a>
      <span class="shoe-desc text-center"><%= shoe.description %></span>
      <%= shoe.price_in_cents %>
       <% end %>
    </div>
    <div class="side-column">
      <aside>
        <h3>Great deals on <br>new products!</h3>
        <img src="<%=Product.all.sample.url%>" />
        <p>
        </p>
      </aside>
      <aside>
      <img src="<%=Product.all.sample.url%>" />
      <p>
        40% off all new products!
      </p>
      </aside>
    </div>
  </div>
  <footer class="footer-pad">Contact Info <br> Adam Hill Email - ahil0017@gmail.com <br> Jake Sena Email - jakesena1994@gmail.com</footer>
</div>

app/views/products/show.html.erb
<nav id="two" class="nav-link">
  <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/skate">Skate</a></li>
    <li><a href="/shoes">Shoes</a></li>
    <li><a href="/apparel">Apparel</a></li>
    <li><a href="/videos">Videos</a></li>
  </ul>
</nav>
<div id="its-soo-late">
<img src="<%= @product.url %>" />

<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p class="review-desc">
  <strong>Description:</strong>
  <%= @product.description %>
</p>


<h3>Reviews</h3>
<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    Added on: <%= review.created_at %>
  </p>
<% end %>

  <h3>New Review</h3>
<%= render 'reviews/form' %>


<%= link_to 'Back', root_path %>
</div>

app/views/products/skate_sort.html.erb
<div id="outer" class="flex_column">
  <a href="/" class="home-link"><header id="one">WynSkate</header></a>
  <nav id="two" class="nav-link">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/skate">Skate</a></li>
      <li><a href="/shoes">Shoes</a></li>
      <li><a href="/apparel">Apparel</a></li>
      <li><a href="/videos">Videos</a></li>
    </ul>
  </nav>
  <div id="center">
    <div id="skate-sort" class="flex_column product-container">
      <% @skate.each do |item|%>
      <img src="<%= item.url%>" class="shoe-image"/>
    <a href="/products/<%= item.id %>" class="text-center">  <%= item.name %> </a>
      <span class="shoe-desc text-center"><%= item.description %></span>
      <%= item.price_in_cents %>
       <% end %>
    </div>
    <div class="flex_column">
      <aside>
        <h3>Great deals on <br>new products!</h3>
        <img src="<%=Product.all.sample.url%>" />
      </aside>
      <aside>
        <img src="<%=Product.all.sample.url%>" />
        <p>40% off all new products!</p>
      </aside>
    </div>
  </div>
  <footer class="footer-pad">Contact Info <br> Adam Hill Email - ahil0017@gmail.com <br> Jake Sena Email - jakesena1994@gmail.com</footer>
</div>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <!-- <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>

  <% if @product.nil? %>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <% else %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <% end %>
<% end %>
<!-- not done with this file -->

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.product.name %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <%= @review.comment %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.name %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |

<% if @review.product.nil? %>
  <%= link_to 'Back', reviews_path %>

<% else %>
  <%= link_to 'Back', @review.product %>
<% end %>

app/views/videos/index.html.erb
<div id="outer" class="flex_column">
  <a href="/" class="home-link"><header id="one">WynSkate</header></a>
  <nav id="two" class="nav-link">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/skate">Skate</a></li>
      <li><a href="/shoes">Shoes</a></li>
      <li><a href="/apparel">Apparel</a></li>
      <li><a href="/videos">Videos</a></li>
    </ul>
  </nav>
  <div id="center">
    <article class="text-center">
      <h1>Top 5 videos of the week!</h1>
      <%= link_to image_tag("Skate_1.png", class:"skate-image text-center"),  "https://www.youtube.com/watch?v=ch_I97FxJio", target: "_blank" %>
      <p id="video-link" ><%= link_to "#1 Hollywood Free park montage", "https://www.youtube.com/watch?v=ch_I97FxJio", target: "_blank" %></p>
      <%= link_to image_tag("Skate_2.png", class:"skate-image"), "https://www.youtube.com/watch?v=hD686Vo-Z8c", target: "_blank" %>
      <p id="video-link"><%= link_to "#2 February 2015 Skate Montage", "https://www.youtube.com/watch?v=hD686Vo-Z8c", target: "_blank" %></p>
      <%= link_to image_tag("Skate_3.png", class:"skate-image"), "https://www.youtube.com/watch?v=pKkuaqinPNY", target: "_blank" %>
      <p id="video-link"><%= link_to "#3 Mickey O'keefe acid drops South Florida", "https://www.youtube.com/watch?v=pKkuaqinPNY", target: "_blank" %></p>
      <%= link_to image_tag("Skate_4.png", class:"skate-image"), "https://www.youtube.com/watch?v=Qfz-SyqRhhA", target: "_blank" %>
      <p id="video-link"><%= link_to "#4 Josiah Gatlyn Full Part 2010", "https://www.youtube.com/watch?v=pKkuaqinPNY", target: "_blank" %></p>
      <%= link_to image_tag("Skate_5.png", class:"skate-image"), "https://www.youtube.com/watch?v=hnZJ89ylmVQ", target: "_blank" %>
      <p id="video-link"><%= link_to "#5 Park Hammerzz!", "https://www.youtube.com/watch?v=hnZJ89ylmVQ", target: "_blank" %></p>
    </article>

    <div class="flex_column">
      <h2 class="new-desc">Video Description</h2>
      <aside class="video-description">
        <h4>#1 Hollywood Free park montage</h4>Majority of of the best clips at OG hollywood freepark. enjoy!
Featuring:Danny Maresca,Holland Cain,EnzoJuarez,Geo Bravo,John Landi,David Teplicki,Omar Bazzan, Puerto-Rican Matt,Jonah Tompson,Mickey O'keefe

Filmed by Mike Suhor and Christian Sims
      </aside>
      <aside class="video-description">
        <h4>#2 February 2015 Skate Montage</h4>Another month of fantastic skateboarding! Featuring Chris Chann, Ty Moss, Josh Katz (myself), Eric Gordon, Jason Nam, Ryan Herron, Patrick Praman, Dan Corrigan, and Ollie Tawoosi.
      </aside>
      <aside class="video-description">
        <h4>#3 Mickey O'keefe acid drops South Florida</h4>It is my pleasure to release this video part of such a dedicated skateboarder and good friend, Mickey O'keefe.

        "PAIN IS WEAKNESS LEAVING THE BODY"

        Filmed by: Mike Suhor and Christian
        Edit:Mike Suhor
      </aside>
      <aside class="video-description">
        <h4>#4 Josiah Gatlyn Full Part 2010</h4>
        instagram: @uskocollective


        instagram: @gatlyngun

Filmed by Josh Cronje, Dean Antoniou, Jack Turner, Mikey Buesso.
      </aside>
      <aside class="video-description">
        <h4>#5 Park Hammerzz!</h4>Had some park footy chillen and decided to make a tage.Some recent footy and some old
        Film/edit: Jordi Aguirre

        Featuring: Geo Bravo, Bobby Berenotto, Lukas Ambraska, Enzo Juarez, Amari Lelaind, Tyler Woods, Joe Jaworski, Anthony Garcia, Jon Spitzer, Holland Cain, Jonah Thompson, Manny Benitez, Mickey O'keefe, Troy Ettienne, Cu-zo
      </aside>
    </div>
  </div>
  <footer class="footer-pad">Contact Info <br> Adam Hill Email - ahil0017@gmail.com <br> Jake Sena Email - jakesena1994@gmail.com</footer>
</div>